### PR TITLE
New Apple Store scene

### PR DESCRIPTION
**Pull request by alicerunsonfedora**
Because Alice needs a new MacBook these days. Preview:
screenshot0052

### CODE REVIEW

**Comment by alicerunsonfedora** [comment]
Whoops, forgot to set the base to nightly, ehehe~

**Comment by sr229** [comment]
Conflic s present, fix them before merging

**Comment by alicerunsonfedora** [comment]
oof

**Comment by sr229** [comment]
You missed some conflict headers, it's failing the builds, please clean it up

**Pull request merged**
